# Generated by Django 4.1 on 2022-08-27 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента должно быть больше 0')], verbose_name='Количество ингридиента'),
        ),
    ]
