# Generated by Django 4.1 on 2022-09-01 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5, 'Количество ингредиента должно быть больше 0')], verbose_name='Количество ингредиента'),
        ),
    ]
